name = "DataFort"
version = "0.1.0"
license = "license"
author = "Renee Gil"
maintainer = "renee.gil@example.com"
copyright = "Copyright 2024, Renee Gil"

[dependencies]
# pFUnit for unit testing
# Uncomment when you install pFUnit:
# pfunit = { git = "https://github.com/Goddard-Fortran-Ecosystem/pFUnit.git" }
[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false
[install]
library = false
[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"

