name: CI

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install gfortran (Ubuntu)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y gfortran

    - name: Install gfortran (macOS)
      if: runner.os == 'macOS'
      run: |
        brew install gcc

    - name: Verify gfortran installation
      run: |
        which gfortran
        gfortran --version

    - name: Install fpm
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          wget https://github.com/fortran-lang/fpm/releases/download/v0.10.0/fpm-0.10.0-linux-x86_64 -O fpm
        else
          wget https://github.com/fortran-lang/fpm/releases/download/v0.10.0/fpm-0.10.0-macos-x86_64 -O fpm
        fi
        chmod +x fpm
        sudo mv fpm /usr/local/bin/

    - name: Build library
      run: fpm build

    - name: Run tests
      run: fpm test

  docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install FORD
      run: |
        pip install ford

    - name: Generate documentation
      run: ford ford.md

    - name: Upload documentation
      uses: actions/upload-artifact@v4
      with:
        name: documentation
        path: docs/

  format-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install fprettify
      run: |
        pip install fprettify

    - name: Check formatting
      run: |
        # Check if any files would be reformatted
        CHANGED=0
        for file in $(find src test app -type f \( -name "*.f90" -o -name "*.F90" \) 2>/dev/null); do
          if ! fprettify --config-file .fprettify.rc --case 1 1 1 1 --diff "$file" | grep -q "^$"; then
            echo "File $file needs formatting"
            fprettify --config-file .fprettify.rc --case 1 1 1 1 --diff "$file"
            CHANGED=1
          fi
        done
        if [ $CHANGED -eq 1 ]; then
          echo "Some files need formatting. Run 'fprettify' locally."
          exit 1
        fi
        echo "All files are properly formatted."